parameters:
#    alerta.example.class: Epublica\AlertaBundle\Example

services:
#    alerta.example:
#        class: %alerta.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
